version: '3' 
services: 
  baota: 
    image: pch18/baota 
    container_name: baota 
    ports: 
      - "80:80" 
      - "443:443" 
      - "8888:8888" 
      - "888:888" 
    privileged: true 
    shm_size: 1g 
    restart: always 
    volumes: 
      - ~/wwwroot:/www/wwwroot 
      - baota_data:/data 
volumes: 
  baota_data:
