version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql-data:/var/lib/mysql
    command: --bind-address=0.0.0.0
volumes:
  mysql-data:
